In [ ]:
import numpy as np
data = np.array([
    [3, 22000, 1, 1],
    [6, 75000, 0, 0],
    [2, 14000, 1, 1],
    [8, 85000, 0, 0],
    [4, 50000, 1, 1]
])


mileage = data[:, 1]

# Calculate Mean and Standard Deviation
mean_mileage = np.mean(mileage)
std_mileage = np.std(mileage)

# Perform Z-Score Normalization
normalized_mileage = (mileage - mean_mileage) / std_mileage

# Replace Original Mileage with Normalized Mileage
data[:, 1] = normalized_mileage

print("Mean of Mileage:", mean_mileage)
print("Standard Deviation of Mileage:", std_mileage)
print("Normalized Data:\n", data)


Mean of Mileage: 49200.0
Standard Deviation of Mileage: 28024.27519134081
Normalized Data:
 [[ 3  0  1  1]
 [ 6  0  0  0]
 [ 2 -1  1  1]
 [ 8  1  0  0]
 [ 4  0  1  1]]


In [ ]:
import numpy as np

X = np.array([
    [3, -0.93, 1],
    [6, 0.88, 0],
    [2, -1.20, 1],
    [8, 1.23, 0],
    [4, 0.03, 1]
])

y = np.array([1, 0, 1, 0, 1])


y_pred = np.array([1.02, 0.62, 1.12, 0.55, 1.01])

errors = y - y_pred

# MSE
mse = np.mean(errors ** 2)

# RMSE
rmse = np.sqrt(mse)

# MAE
mae = np.mean(np.abs(errors))

# R-Squared (R²)
y_mean = np.mean(y)
ss_total = np.sum((y - y_mean) ** 2)
ss_residual = np.sum((y - y_pred) ** 2)
r_squared = 1 - (ss_residual / ss_total)

print("\nError Metrics:")
print(f"Mean Squared Error (MSE): {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"R-Squared (R²): {r_squared:.4f}")



Error Metrics:
Mean Squared Error (MSE): 0.1404
Root Mean Squared Error (RMSE): 0.3746
Mean Absolute Error (MAE): 0.2640
R-Squared (R²): 0.4152
