In [ ]:
import numpy as np

X = np.array([
    [3, 22000, 1],
    [6, 75000, 0],
    [2, 14000, 1],
    [8, 85000, 0],
    [4, 50000, 1]
])

y = np.array([1, 0, 1, 0, 1])

w = np.zeros(X.shape[1] + 1)  
alpha = 0.01  
iterations = 1000

# Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def loss_function(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Training using Gradient Descent
for i in range(iterations):
    # Add Bias Term (x0 = 1)
    X_bias = np.c_[np.ones(X.shape[0]), X]

    # Calculate Linear Combination (z = w0 + w1*x1 + w2*x2 + w3*x3)
    z = np.dot(X_bias, w)

    # Apply Sigmoid Function
    y_pred = sigmoid(z)

    # Compute Loss
    loss = loss_function(y, y_pred)

    # Calculate Gradients
    gradient = np.dot(X_bias.T, (y_pred - y)) / len(y)

    # Update Weights
    w -= alpha * gradient

    # Print loss every 100 iterations
    if i % 100 == 0:
        print(f"Iteration {i}, Loss: {loss}")

print("\nFinal Weights:", w)

# Prediction Function
def predict(X_new):
    X_new_bias = np.c_[np.ones(X_new.shape[0]), X_new]
    z = np.dot(X_new_bias, w)
    return (sigmoid(z) >= 0.5).astype(int)

y_pred = predict(X)

def confusion_matrix(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    TN = np.sum((y_true == 0) & (y_pred == 0))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    return np.array([[TP, FP], [FN, TN]])

cm = confusion_matrix(y, y_pred)
print("\nConfusion Matrix:\n", cm)

def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

def precision(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    FP = np.sum((y_true == 0) & (y_pred == 1))
    return TP / (TP + FP) if (TP + FP) > 0 else 0

def recall(y_true, y_pred):
    TP = np.sum((y_true == 1) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    return TP / (TP + FN) if (TP + FN) > 0 else 0

def f1_score(y_true, y_pred):
    p = precision(y_true, y_pred)
    r = recall(y_true, y_pred)
    return 2 * (p * r) / (p + r) if (p + r) > 0 else 0

print(f"Accuracy: {accuracy(y, y_pred):.2f}")
print(f"Precision: {precision(y, y_pred):.2f}")
print(f"Recall: {recall(y, y_pred):.2f}")
print(f"F1 Score: {f1_score(y, y_pred):.2f}")


Iteration 0, Loss: 0.6931471805599453
Iteration 100, Loss: nan
Iteration 200, Loss: nan
Iteration 300, Loss: nan
Iteration 400, Loss: nan
Iteration 500, Loss: nan
Iteration 600, Loss: nan
Iteration 700, Loss: nan
Iteration 800, Loss: nan
Iteration 900, Loss: nan

Final Weights: [ 2.505  1.923 46.     3.903]

Confusion Matrix:
 [[3 2]
 [0 0]]
Accuracy: 0.60
Precision: 0.60
Recall: 1.00
F1 Score: 0.75


/tmp/ipykernel_21061/178846135.py:22: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/tmp/ipykernel_21061/178846135.py:26: RuntimeWarning: divide by zero encountered in log
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
/tmp/ipykernel_21061/178846135.py:26: RuntimeWarning: invalid value encountered in multiply
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))


In [2]:
import numpy as np

# Dataset: [Car Age, Mileage, Fuel Type]
X = np.array([
    [3, 22000, 1],
    [6, 75000, 0],
    [2, 14000, 1],
    [8, 85000, 0],
    [4, 50000, 1]
])

# Target Variable: Price Category (0 or 1)
y = np.array([1, 0, 1, 0, 1])

# Initialize Weights and Bias
w = np.zeros(X.shape[1] + 1)  # [w0, w1, w2, w3]
alpha = 0.01  # Learning Rate
iterations = 10  # Reduced for easy viewing

# Sigmoid Function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Loss Function (Binary Cross Entropy)
def loss_function(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

# Training using Gradient Descent
for i in range(iterations):
    # Add Bias Term (x0 = 1)
    X_bias = np.c_[np.ones(X.shape[0]), X]

    # Calculate Linear Combination (z = w0 + w1*x1 + w2*x2 + w3*x3)
    z = np.dot(X_bias, w)

    # Apply Sigmoid Function
    y_pred = sigmoid(z)

    # Compute Loss
    loss = loss_function(y, y_pred)

    # Calculate Gradients
    gradient = np.dot(X_bias.T, (y_pred - y)) / len(y)

    # Update Weights
    w -= alpha * gradient

    # Print All Values
    print(f"Iteration {i+1}")
    print("X_bias (With Bias Term Added):")
    print(X_bias)
    print("\nLinear Combination (z):")
    print(z)
    print("\nPredicted Values (y_pred):")
    print(y_pred)
    print("\nLoss:", loss)
    print("\nGradient:")
    print(gradient)
    print("\nUpdated Weights (w):")
    print(w)
    print("-" * 80)


Iteration 1
X_bias (With Bias Term Added):
[[1.0e+00 3.0e+00 2.2e+04 1.0e+00]
 [1.0e+00 6.0e+00 7.5e+04 0.0e+00]
 [1.0e+00 2.0e+00 1.4e+04 1.0e+00]
 [1.0e+00 8.0e+00 8.5e+04 0.0e+00]
 [1.0e+00 4.0e+00 5.0e+04 1.0e+00]]

Linear Combination (z):
[0. 0. 0. 0. 0.]

Predicted Values (y_pred):
[0.5 0.5 0.5 0.5 0.5]

Loss: 0.6931471805599453

Gradient:
[-1.0e-01  5.0e-01  7.4e+03 -3.0e-01]

Updated Weights (w):
[ 1.0e-03 -5.0e-03 -7.4e+01  3.0e-03]
--------------------------------------------------------------------------------
Iteration 2
X_bias (With Bias Term Added):
[[1.0e+00 3.0e+00 2.2e+04 1.0e+00]
 [1.0e+00 6.0e+00 7.5e+04 0.0e+00]
 [1.0e+00 2.0e+00 1.4e+04 1.0e+00]
 [1.0e+00 8.0e+00 8.5e+04 0.0e+00]
 [1.0e+00 4.0e+00 5.0e+04 1.0e+00]]

Linear Combination (z):
[-1628000.011 -5550000.029 -1036000.006 -6290000.039 -3700000.016]

Predicted Values (y_pred):
[0. 0. 0. 0. 0.]

Loss: nan

Gradient:
[-6.00e-01 -1.80e+00 -1.72e+04 -6.00e-01]

Updated Weights (w):
[7.0e-03 1.3e-02 9.8e+01 9.0e-0

/tmp/ipykernel_21061/1836848120.py:22: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/tmp/ipykernel_21061/1836848120.py:26: RuntimeWarning: divide by zero encountered in log
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
/tmp/ipykernel_21061/1836848120.py:26: RuntimeWarning: invalid value encountered in multiply
  return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
